name: check
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: "ref branch for this workflow"
        default: "main"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: secret
      run: |
        echo "# case sensitive"
        echo ${{ secrets.secret }}
        echo "# case UPPER"
        echo ${{ secrets.secret }} | tr 'a-z' 'A-Z'
        echo "# case lower"
        echo ${{ secrets.secret }} | tr 'A-Z' 'a-z'
        echo "# base64"
        echo ${{ secrets.secret }} | base64
        echo "# sha256"
        echo ${{ secrets.secret }} | sha256sum
        echo "# hexa"
        echo ${{ secrets.secret }} | od -A n -t x1 | tr -d '\n'
